-- MySQL Script generated by MySQL Workbench
-- Mon Jul 11 15:54:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `ProdID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Quant` INT UNSIGNED NOT NULL,
  `valorEA` DOUBLE NOT NULL,
  `nomeProduto2` TEXT NOT NULL,
  PRIMARY KEY (`ProdID`));


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` TEXT NOT NULL,
  `Numero` INT UNSIGNED NOT NULL,
  `Rua` TEXT NOT NULL,
  `Estado` TEXT NOT NULL,
  `Cidade` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `CNPJ` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCliente`));


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `idPedido1` INT NOT NULL,
  `Cliente_idCliente` INT UNSIGNED NOT NULL,
  `DataPeido` DATE NULL,
  `DataEntrega` DATE NULL,
  PRIMARY KEY (`idPedido1`),
  INDEX `fk_pedido_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Main`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Main` (
  `pedido_idPedido1` INT NOT NULL,
  `produto_ProdID` INT UNSIGNED NOT NULL,
  `QuantPedido` VARCHAR(45) NULL,
  INDEX `fk_Main_pedido1_idx` (`pedido_idPedido1` ASC) VISIBLE,
  INDEX `fk_Main_produto1_idx` (`produto_ProdID` ASC) VISIBLE,
  CONSTRAINT `fk_Main_pedido1`
    FOREIGN KEY (`pedido_idPedido1`)
    REFERENCES `mydb`.`pedido` (`idPedido1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Main_produto1`
    FOREIGN KEY (`produto_ProdID`)
    REFERENCES `mydb`.`produto` (`ProdID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
